### Get all users
GET http://localhost:8000/users

### Get user by ID
GET http://localhost:8000/users/68ca217ca9b80013dde209ee

### Create User
POST http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "username": "test1@test.com",
    "firstName": "John",
    "lastName": "Doe",
    "email": "test@example.com"
}

### Update User
POST http://localhost:8000/users/68ca22a3a9b80013dde209ef HTTP/1.1
content-type: application/json

{
    "username": "test1@test.com",
    "firstName": "John",
    "lastName": "Doe",
    "email": "test@example.com"
}

### Delete Contact
DELETE http://localhost:8000/users/68ca22a3a9b80013dde209ef